# Generated by Django 5.0.7 on 2024-08-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_blogcategory_alter_blogpost_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_fields=('id', 'slug'),
        ),
    ]
