# Generated by Django 5.0.7 on 2024-08-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_product_id_slug_shop_produc_id_f21274_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_id_f21274_idx',
        ),
    ]
